# C:\projects\TR\projeto\projeto-01b\src\omnetpp.ini
[General]
network = src.WifiJammingNetwork
sim-time-limit = 3s
output-scalar-file = results.sca
output-vector-file = results.vec
record-eventlog = true


*.sender.wlan[0].mac.autoStart = true
*.receiver.wlan[0].mac.autoStart = true
*.receiver.app[0].startTime = 0s

# =====================
# CONFIGURAÇÃO DE REDE
# =====================
*.configurator.typename = "Ipv4NetworkConfigurator"
*.configurator.addStaticRoutes = true
*.configurator.addDefaultRoutes = true
*.configurator.assignDisjunctSubnetAddresses = true
*.configurator.optimizeRoutes = true
*.configurator.verbose = true
*.**.routingTable.printRoutingTable = true
*.configurator.printAddresses = true

# IGNORAR receiver na autoconfiguração para usar IP fixo
# *.configurator.ignoreModuleNames = "receiver"
*.configurator.ignoreModuleNames = "**.receiver"

# ================
# CONFIGURAÇÃO IPs
# ================
*.receiver.hasIpv4 = true
*.receiver.wlan[0].ipv4.address = "10.0.0.2"
*.receiver.wlan[0].ipv4.netmask = "255.255.255.0"

# =====================
# CONFIGURAÇÃO DAS APPS
# =====================

# RECEIVER
*.receiver.app[0].typename = "UdpSink"
*.receiver.app[0].localPort = 8080

# SENDER
*.sender.numApps = 1
*.sender.app[0].typename = "UdpBasicApp"
*.sender.app[0].destAddresses = "10.0.0.2"
*.sender.app[0].destPort = 8080
*.sender.app[0].messageLength = 1000B
*.sender.app[0].sendInterval = 0.1s
*.sender.app[0].startTime = 0.08s
*.sender.app[0].stopTime = 1.9s

# JAMMER
#*.jammer.transmitter.typename = "NoiseDimensionalTransmitter"
#*.jammer.transmitter.power = 10mW
#*.jammer.transmitter.bandwidth = 20MHz
#*.jammer.transmitter.centerFrequency = 2.4GHz
#*.jammer.transmitter.duration = 0.2s
#*.jammer.sleepInterval = 0.8s
#*.jammer.stopTime = 9.9s 
#*.jammer.activeTime = 9.9s 


# Definir quantidade de interfaces
*.sender.numWlanInterfaces = 1
*.receiver.numWlanInterfaces = 1

# Parâmetros de Wi-Fi
*.**.wlan[0].radio.transmitter.power = 200mW
*.**.wlan[0].radio.receiver.sensitivity = -85dBm
*.**.wlan[0].mac.ssid = "testwifi"
*.**.wlan[0].mac.useAck = true
*.**.wlan[0].radio.mediumModule = "^.radioMedium"

# Visualização dos pacotes (LINHAS VISUAIS)
**.wlan[0].radio.displayCommunicationRange = true
*.visualizer.*.mediumVisualizer.displaySignals = true
*.visualizer.*.mediumVisualizer.signalPropagationAnimation = true
*.visualizer.*.mediumVisualizer.packetAnimation = true
*.visualizer.*.mediumVisualizer.displayCommunicationRanges = true

# Adicional: registre interferência
*.visualizer.*.mediumVisualizer.displayNoise = true
**.radio.interferenceNoisePower.vector-recording = true

# ===================
# PARÂMETROS DE RÁDIO
# ===================
*.radioMedium.backgroundNoise.power = -110dBm
*.radioMedium.typename = "DimensionalRadioMedium" # para controlar configuração de não terminar simulação ao pausar  o jammer
*.radioMedium.maxTransmissionDuration = 2s


# ===========================
# PROTOCOLOS DE CAMADA DE REDE
# ===========================
*.**.ipv4.arp.typename = "GlobalArp"
*.**.routingTable.typename = "Ipv4RoutingTable"

# Gravar estatísticas de pacotes enviados e recebidos
# Vetores específicos
**.udpBasicApp.packetSent.vector-recording = true
**.udpSink.packetReceived.vector-recording = true
**.udpSink.packetLost.vector-recording = true
**.udpSink.packetReceived.scalar-recording = true
**.udpBasicApp.packetSent.scalar-recording = true
**.udpBasicApp.recordStatistics = true
**.udpSink.recordStatistics = true