[General]
[Config Wireless001]
network = src.recording
description = Comunicação entre 2 hosts Wireless
sim-time-limit = 20s

# Rede
*.host*.ipv4.arp.typename = "GlobalArp" #*.host*.networkLayer.arpType = "GlobalArp"

# Aplicativo de envio (hostA)
*.hostA*.numApps = 1
*.hostA.app[0].typename = "UdpBasicApp"
*.hostA.app[0].destAddresses = "hostB"
*.hostA.app[0].messageLength = 1000B
*.hostA.app[0].sendInterval = exponential(12ms)
*.hostA.app[0].packetName = "UDPdata"
*.hostA.app[0].destPort = 5000

# Aplicativo de recepção (hostB)
*.hostB*.numApps = 1
*.hostB.app[0].typename = "UdpSink"
*.hostB.app[0].localPort = 5000

# NIC e alcance
*.host*.wlan[0].typename = "AckingWirelessInterface"
*.host*.wlan[0].mac.useAck = false
*.host*.wlan[0].mac.fullduplex = false
*.host*.wlan[0].radio.receiver.ignoreInterference = true # trocar isso para testar jammer
*.host*.wlan[0].radio.transmitter.communicationRange = 500m
*.host*.wlan[0].mac.headerLength = 23B

#*.host*.wlan[0].radio.receiver.typename = "DimensionalReceiver"
#*.host*.wlan[0].radio.transmitter.typename = "DimensionalTransmitter"

# Velocidade
*.host*.**.bitrate = 1Mbps


# Visualização dos pacotes
*.visualizer.*.mediumVisualizer.displaySignals = true
*.visualizer.*.mediumVisualizer.signalPropagationAnimation = true
*.visualizer.*.mediumVisualizer.packetAnimation = true
*.visualizer.*.mediumVisualizer.displayCommunicationRanges = true

# Registro de interferência
*.visualizer.*.mediumVisualizer.displayNoise = true
**.radio.interferenceNoisePower.vector-recording = false # trocar isso para testar jammer

# Meio de rádio (backgroundNoise)
#*.radioMedium.typename = "IdealRadioMedium"#"DimensionalRadioMedium"

*.radioMedium.backgroundNoise.power = -110dBm