# C:\projects\TR\projeto\projeto-02b\src\omninetpp.ini

[Config Wireless001]
network = src.recording
sim-time-limit = 4s

output-scalar-file = results.sca
output-vector-file = results.vec
record-eventlog = true

# =======================
# IP e Roteamento
# =======================
*.configurator.typename                     = "Ipv4NetworkConfigurator"
*.configurator.addStaticRoutes              = true
*.configurator.addDefaultRoutes             = true
*.configurator.assignDisjunctSubnetAddresses = true
*.configurator.optimizeRoutes               = true

# =======================
# Aplicações UDP
# =======================
*.sender.numApps                 = 1
*.sender.app[0].typename         = "UdpBasicApp"
*.sender.app[0].destAddresses    = "10.0.0.2"
*.sender.app[0].destPort         = 8080
*.sender.app[0].messageLength    = 1000B
*.sender.app[0].sendInterval     = 0.1s
*.sender.app[0].startTime        = 1s
*.sender.app[0].stopTime         = 4s

*.receiver.numApps               = 1
*.receiver.app[0].typename       = "UdpSink"
*.receiver.app[0].localPort      = 8080

# =======================
# Configuração Wi-Fi AD-HOC (IBSS)
# =======================
# Garantir que cada AdhocHost use uma única interface
*.sender.numWlanInterfaces       = 1
*.receiver.numWlanInterfaces     = 1

# Potência e sensibilidade
# =======================
*.radioMedium.backgroundNoise.power   = -110dBm


# Visualizações
# =======================
**.wlan[0].radio.displayCommunicationRange                 = true

# =======================
# Estatísticas
# =======================
**.udpBasicApp.packetSent.vector-recording = true
**.udpSink.packetReceived.vector-recording  = true
**.udpSink.packetLost.vector-recording      = true
**.udpSink.packetReceived.scalar-recording  = true
**.udpBasicApp.packetSent.scalar-recording  = true

# =============
# Jammer
# ============

# método 2: adicionar JammingApp se quiser controlar via app
*.jammer.numApps = 1
*.jammer.app[0].typename = "JammingApp"
*.jammer.app[0].startTime = 2s
*.jammer.app[0].stopTime = 4s
